###
http://localhost:8000/api/users/
###
http://localhost:8000/api/users/about_me
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
###
POST http://localhost:8000/api/users
content-type: application/json

{
    "email": "user2@gmail.com",
    "password": "user2",
    "first_name": "user2 first_name",
    "last_name": "user2 last_name",
    "role_id": 2,
    "phone": "112",
    "gender": true
}
###
PUT http://localhost:8000/api/users/4
content-type: application/json

{
    "email": "user1@gmail.com",
    "password": "user1",
    "first_name": "user1 put1",
    "last_name": "user1 new",
    "role_id": 4,
    "phone": "111 new",
    "gender": false
}
###
DELETE http://localhost:8000/api/users/4
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9



### ### ###

